### ISSUE TITLE
Incorrect type assigned to result of exec()

### ISSUE THREAD

**Issue by Raul52** [zhan-huang/js-solr-highlighter#1]
Hello,

If you are having a tsconfig using `strictNullChecks` to true, the library will fail to build.

`Error: node_modules/js-solr-highlighter/index.ts:106:11 - error TS2322: Type 'RegExpExecArray | null' is not assignable to type 'RegExpExecArray'.
  Type 'null' is not assignable to type 'RegExpExecArray'.`
  
Can you please adapt the code and change the line 96 to `  let res: RegExpExecArray | null`?

Thank you!

**Comment by zhan-huang** [comment]
Hi,

Make sense to me. I will do as required today.

Thank you for your feedback!

**Comment by zhan-huang** [comment]
Changed as required (also deployed to npm). Close this issue now.
