### ISSUE TITLE
Support of wildcards

### ISSUE THREAD

**Issue by Raul52** [zhan-huang/js-solr-highlighter#2]
Hello,

If I have a word containing the `*` wildcard, the highlighting will not work as expected.

The normal case will work:
```javascript
var query = 'cancer'
var content = 'Platelet Volume Is Reduced In Metastasing Breast Cancer: Blood Profiles Reveal Significant Shifts.'
```
Output: cancer **will be** highlighted

The asterisk case will not work:
```javascript
var query = 'canc*'
var content = 'Platelet Volume Is Reduced In Metastasing Breast Cancer: Blood Profiles Reveal Significant Shifts.'
```
Output: cancer **will not be** highlighted

Can this request be handled by the current version of the library?

All the best,
Raul

**Comment by zhan-huang** [comment]
Thank you for your investigation. I will investigate it and update you shortly.

**Comment by Raul52** [comment]
Hello Zhan,

Any news?

**Comment by zhan-huang** [comment]
Hi Raul,

Sorry for replying late. I got your idea, I was discussing it with my colleagues in order to consider the effect of the change on our product. I was also investigating how best to implement it. I will update you in 1-2 days.

Cheers

**Comment by zhan-huang** [comment]
Hi Raul,

Sorry for replying late. I start to add the wildcards case which may take several days. I will update you once it's done. 

BTW, you are more than welcome to folk this repo. 

Cheers

Zhan

**Comment by zhan-huang** [comment]
Done.

**Comment by Raul52** [comment]
@zhan-huang I hope I do not stress you too much :).

Did you also consider the case of starting with `*` ? 
```
var query = '*ancer'
```

Also starting and ending with `*` ?
```
var query = '*anc*'
```


We need this case also and I think it will further improve the library.
